# Generated by Django 3.2.6 on 2021-08-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_patientrecords_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecords',
            name='medical_history',
            field=models.ManyToManyField(related_name='medical_history', to='app.MedicalHistory'),
        ),
        migrations.AddField(
            model_name='patientrecords',
            name='treatment_info',
            field=models.ManyToManyField(related_name='treatment_info', to='app.TreatmentInfo'),
        ),
        migrations.AlterField(
            model_name='patientrecords',
            name='attending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
